#!/bin/bash
#
# Settings for firstboot scripts
#
# NOTE: This file is named 00-config-settings to make sure it loads first, don't make anything load sooner than this file!
#
source $(dirname $ME)/../../common/global.config
source $(dirname $ME)/../../common/basebox.config

if [ -z "$PACKAGES" ]; then
    msg "** SOMETHING IS WRONG PACKAGES=[$PACKAGES]!!! **"
    exit 255
fi
