#!/bin/bash
#
# Settings for firstboot scripts
#
# NOTE: This file is named 00-config-settings to make sure it loads first, don't make anything load sooner than this file!
#
## Must run as root
[ $(id -u) -eq 0 ] || error "$ME must run as root, try: sudo $ME" 100
#
## Common configs
source $(dirname $ME)/../../common/global.config
source $(dirname $ME)/../../common/basebox.config
#
## Sanity check
if [ -z "$PACKAGES" ]; then
    msg "** SOMETHING IS WRONG PACKAGES=[$PACKAGES]!!! **"
    exit 255
fi
