#!/bin/bash
if dpkg -s sysvinit-core > /dev/null; then
    :
else
    apt-get -y install sysvinit-core sysvinit-utils
    cp /usr/share/sysvinit/inittab /etc/inittab
    sed -i '/^[0-9]:23:.*getty/s/^/# /' /etc/inittab
    echo -e 'Package: systemd\nPin: release *\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
    echo -e '\n\nPackage: *systemd*\nPin: release *\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
fi
if dpkg -s systemd; then
    apt-get -y remove --purge --auto-remove systemd || true
fi
