#!/bin/bash
(
    if dpkg -s sysvinit-core > /dev/null; then
        :
    else
        notice "Installing sysvinit"
        apt-get -y install sysvinit-core sysvinit-utils
        cp /usr/share/sysvinit/inittab /etc/inittab
        sed -i '/^[0-9]:23:.*getty/s/^/# /' /etc/inittab
    fi
    if dpkg -s systemd > /dev/null; then
        notice "Removing systemd"
        if apt-get -y remove --purge --auto-remove systemd; then
            echo -e 'Package: systemd\nPin: release *\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
            echo -e '\n\nPackage: *systemd*\nPin: release *\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
            notice "systemd removed"
        fi
    fi
)
