#!/bin/bash
#
# 15customize - Customize system settings
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:42:16 EST 2015
#

usermod -c "vagrant" vagrant
usermod vagrant -a -G adm

# Setup for auto-update
cat << '!' > /.swgemudev.update
#!/bin/bash
(set -x;/usr/bin/perl -ne '$b="master";if(/zdbranch=(\S+)/){$b=$1} END {($u,$g,$ENV{"HOME"})=(getpwnam("vagrant"))[2,3,7];$)=$g;$>=$u;system("cd;id -a;pwd;set -x;pwd;git clone https://github.com/lordkator/ZonamaDev.git;cd ZonamaDev;git stash;git fetch;git checkout $b;git pull");}' /proc/cmdline)2>&1|logger -t $0
!

chmod 700 /.swgemudev.update

# Add rc.fasttrak
if [ ! -d /etc/systemd ]; then
    echo "Using /etc/rc.local for rc.fasttrack"
    echo -e '## ZonamaDev Boot\n/.swgemudev.update\n/home/vagrant/ZonamaDev/fasttrack/scripts/rc.fasttrack' >> /etc/rc.local
    sed -e '/^exit/{H;d}' -e '${p;x}' -i /etc/rc.local
    return
fi

echo "Using systemd for rc.fasttrack"

cat << ! > /lib/systemd/system/rc.fasttrack.service
# This file is part of ZonamaDev
#
# See https://github.com/lordkator/ZonamaDev for more details
#
[Unit]
Description=ZonamaDev Boot Script
Documentation=https://github.com/lordkator/ZonamaDev
Before=systemd-user-sessions.service
After=dbus.socket

[Service]
Type=forking
ExecStartPre=/.swgemudev.update
ExecStart=/home/vagrant/ZonamaDev/fasttrack/scripts/rc.fasttrack
TimeoutSec=0
RemainAfterExit=yes
StandardOutput=null
StandardError=null

[Install]
WantedBy=multi-user.target
!

systemctl enable rc.fasttrack
