#!/bin/bash
#
# 15customize - Customize system settings
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:42:16 EST 2015
#

usermod -c "${ZDUSER}" ${ZDUSER}
usermod ${ZDUSER} -a -G adm

# Setup for auto-update
cat << ! > /.swgemudev.update
#!/bin/bash -x
(
    export ZDUSER='${ZDUSER}'
    export ZONAMADEV_URL='${ZONAMADEV_URL}'
    export ZONAMADEV_BRANCH='release-1.5'
    source ~${ZDUSER}/ZonamaDev/common/global.config
!
cat << '!' >> /.swgemudev.update
    repo=$(VBoxControl --nologo guestproperty get "/ZonamaDev/url"|sed -e 's/^.*: //' -e 's/^No value.*//' 2> /dev/null);repo=${repo:-$ZONAMADEV_URL}
    branch=$(VBoxControl --nologo guestproperty get "/ZonamaDev/branch"|sed -e 's/^.*: //' -e 's/^No value.*//' 2> /dev/null);branch=${branch:-$ZONAMADEV_BRANCH}
    githost=$(echo "${repo}"|sed -e 's!.*//!!' -e 's!/.*!!')
    while ! host -T -W 5 -t A ${githost}; do sleep 1; done
    /usr/bin/perl -ne 'BEGIN{$r="'${repo}'";$b="'${branch}'"} $b=$1 if(/zdbranch=(\S+)/);$r=$1 if(/zdrepo=(\S+)/); END{($u,$g,$ENV{"HOME"})=(getpwnam($ENV{"ZDUSER"}))[2,3,7];$)=$g;$>=$u;system("cd;id -a;pwd;set -x;pwd;git clone $r;cd ZonamaDev;git stash;git fetch;git checkout $b;git pull");}' /proc/cmdline
) 2>&1 |logger -t $0
!

chmod 700 /.swgemudev.update

# Add rc.fasttrak
if dpkg -s sysvinit-core > /dev/null; then
    echo "Using /etc/rc.local for rc.fasttrack"
    sed -i '/^## ZonamaDev Boot/,+3d' /etc/rc.local
    echo -e "## ZonamaDev Boot\n/.swgemudev.update\n${ZDHOME}/ZonamaDev/fasttrack/scripts/rc.fasttrack" >> /etc/rc.local
    sed -e '/^exit/{H;d}' -e '${p;x}' -i /etc/rc.local
    return
fi

echo "Using systemd for rc.fasttrack"

cat << ! > /lib/systemd/system/rc.fasttrack.service
# This file is part of ZonamaDev
#
# See https://github.com/Zonama/ZonamaDev for more details
#
[Unit]
Description=ZonamaDev Boot Script
Documentation=https://github.com/Zonama/ZonamaDev
Before=lightdm.service
After=network-online.target auditd.service nss-lookup.target

[Service]
Type=forking
ExecStartPre=/.swgemudev.update
ExecStart=${ZDHOME}/ZonamaDev/fasttrack/scripts/rc.fasttrack
TimeoutSec=180
RemainAfterExit=yes
StandardOutput=null
StandardError=null

[Install]
WantedBy=multi-user.target
!

systemctl daemon-reload
systemctl enable rc.fasttrack
