#!/bin/bash
#
# 20updates - update packages
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:42:16 EST 2015
#

# Add Googles's chrome repo to sources
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

(
    # die on error
    set -e

    # Make sure we don't prompt with confusing things
    unset UCF_FORCE_CONFFOLD
    export UCF_FORCE_CONFFNEW=YES
    ucf --purge /boot/grub/menu.lst

    export DEBIAN_FRONTEND=noninteractive

    # exit if anything returns error

    # Get latest repo locations
    apt-get update

    # Upgrade whatever we can
    for i in 1 2 3
    do
        if apt-get -y -o Dpkg::Options::="--force-confnew" dist-upgrade; then
            break
        else
            notice "apt-get dist-upgrade failed RET=$? RETRY=$i"
        fi
    done

    msg "Install Packages"

    echo ">> PACKAGES: $PACKAGES $EXTRAS"

    for i in 1 2 3
    do
        if apt-get -y install $PACKAGES $EXTRAS; then
            break
        else
            notice "apt-get failed RET=$? RETRY=$i"
        fi
    done

    apt-get -y autoremove

    if dpkg -s sysvinit-core > /dev/null; then
        :
    else
        # Start out in text console until vbguest can update video drivers
        systemctl set-default -f multi-user.target

        # Wait a bit for network to start
        systemctl enable systemd-networkd-wait-online
    fi
)

ret=$?
if [ ${ret} -ne 0 ]; then
    msg "ERROR: ${ME} returned ${ret}"
    exit ${ret}
fi
