#!/bin/bash
#
# 25atom - Install Atom
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Wed Dec 28 05:47:01 EST 2016
#

if [ -z "$ATOM_URL" ]; then
    msg "** Missing ATOM_URL? Can't download and install!"
    return
fi

(
    echo "Install Atom from $ATOM_URL"

    cd ${ZDHOME}
    mkdir Downloads || echo "Created Downloads directory"
    cd Downloads
    if wget --progress=dot:giga "$ATOM_URL" -o atom.deb; then
	:
    else
	echo "** wget returned $?"
	exit $?
    fi

    ATOM_FN=$PWD/$(basename "$ATOM_URL")

    if [ ! -f $ATOM_FN ]; then
	echo "** Can't find downloaded file"
	exit 100
    fi
    set -x
    cd ${ZDHOME}
    dpkg -i $ATOM_FN
    apt-get install -y -f
    sudo -u "${ZDUSER}" /bin/bash -xc "cd ~${ZDUSER};apm install ${ATOM_PACKAGES}"
)
