#!/bin/bash
#
# 25eclipse - Install Eclipse
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:44:34 EST 2015
#

if [ -z "$ECLIPSE_URL" ]; then
    msg "** Missing ECLIPSE_URL? Can't download and install!"
    return
fi

(
    echo "Install Eclipse from $ECLIPSE_URL"

    ECLIPSE_FN="${ZDHOME}/Downloads/eclipse.tar.gz"

    cd ${ZDHOME}
    mkdir Downloads || echo "Created Downloads directory"
    cd Downloads
    if wget -O "${ECLIPSE_FN}" --progress=dot:giga "$ECLIPSE_URL"; then
	:
    else
	echo "** wget returned $?"
	exit $?
    fi

    if [ ! -f "${ECLIPSE_FN}" ]; then
	echo "** Can't find downloaded file"
	exit 100
    fi
    cd ${ZDHOME}
    tar xf "${ECLIPSE_FN}"
)
