#!/bin/bash
#
# 25eclipse - Install Eclipse
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:44:34 EST 2015
#

if [ -z "$ECLIPSE_URL" ]; then
    msg "** Missing ECLIPSE_URL? Can't download and install!"
    return
fi

(
    echo "Install Eclipse from $ECLIPSE_URL"

    cd ${ZDHOME}
    mkdir Downloads || echo "Created Downloads directory"
    cd Downloads
    if wget --progress=dot:giga "$ECLIPSE_URL"; then
	:
    else
	echo "** wget returned $?"
	exit $?
    fi

    ECLIPSE_FN=$PWD/$(basename "$ECLIPSE_URL")

    if [ ! -f $ECLIPSE_FN ]; then
	echo "** Can't find downloaded file"
	exit 100
    fi
    cd ${ZDHOME}
    tar xf $ECLIPSE_FN
)
