#!/bin/bash
#
# 30apply-patches - Apply patch files
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:46:04 EST 2015
#

for i in $(dirname $ME)'/../patches/'*
do
    msg "Patch $i: APPLY"
    tmp="/tmp/"$(basename "${i}")
    sed  -e 's!\${ZDUSER}!'"${ZDUSER}"'!g' -e 's!\${ZDHOME}!'"${ZDHOME}"'!g' "${i}" > "${tmp}"
    if (cd /;exec patch --verbose -p0 -Nft) < "${tmp}"; then
	msg "Patch $i: SUCCESS"
	rm -f "${tmp}"
    else
	st=$?
	if [ $st -eq 1 ]; then
	    msg "Patch ${tmp}: WARNING, Returned $st"
	else
	    msg "Patch ${tmp}: FAILED! Returned $st"
	    exit 12
	fi
    fi
done
