#!/bin/bash
#
# 35berkeley-db - Build swgemu compat bdb
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Tue Dec 29 05:13:34 EST 2015
#

if [ -f ${BDB_DIR}/include/db.h ]; then
    echo "Looks like ${BDB_URL} is already installed"
    echo "Do: sudo rm -fr ${BDB_DIR} to force rebuild"
    return 0
fi

(
    umask 022

    tmpdir=$(mktemp -d /tmp/$(basename $ME).XXXXXX)

    echo "Using ${tmpdir} for download and build."

    chmod 755 ${tmpdir}

    cd ${tmpdir}

    wget --progress=dot:mega ${BDB_URL}

    fn=$(basename "${BDB_URL}")

    [ -f "$fn" ] || error "Failed to download Berkeley DB Tar from ${BDB_URL}, look in ${tmpdir} for clues." 135

    tar xf ${fn}

    tm_lastrpt=$SECONDS
    lines=0

    echo "Building & Installing..."
    (
	trap 'st=$?;exec 1>&2;error "UNEXPECTED EXIT FROM BUILD" $st' 0
	set -xe
	cd db-*/build_unix
	pwd
	../dist/configure --enable-cxx
	nproc=$(type -P nproc)

	if [ -n "$nproc" ]; then
	    args='-j'$($nproc)
	fi
	make $args 2> ${tmpdir}/make.err | tee make.out
	make install
	echo "${BDB_DIR}/lib" >> /etc/ld.so.conf
	ldconfig
	trap - 0
    ) | tee build.out | while read ln
    do
	let "lines=$lines + 1"
	let "tm_delta=$SECONDS - $tm_lastrpt"
	if [ $tm_delta -ge 5 ]; then
	    echo "Building: $lines lines of output so far."
	    tm_lastrpt=$SECONDS
	fi
    done

    [ -f ${BDB_DIR}/include/db.h ] || error "Failed to build Berkeley DB from ${BDB_URL}, look in ${tmpdir} for clues." 135

    cd $HOME

    rm -fr ${tmpdir}
)
