#!/bin/bash
#
# 40lua53 - Get LUA 5.3
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Tue Dec 29 07:05:21 EST 2015
#

LUA_BIGNUM='4611686018427387904' # 2^62

if $FORCE; then
    echo "Force rebuild of lua53"
else
    if [ -d ${LUA53_TEST_DIR} ]; then
	# Check of we have 64 bit ints
	bignum=$(echo 'print('${LUA_BIGNUM}')' | /usr/local/bin/lua -)
	if [ "$bignum" != "${LUA_BIGNUM}" ]; then
	    echo "** /usr/local/bin/lua not built with 64bit ints!"
	    echo "** Will rebuild with LNUM_INT64"
	else
	    echo "Looks like ${LUA53_URL} is already installed"
	    echo "To force rebuild do: sudo rm -f ${LUA53_TEST_DIR}"
	    return 0
	fi
    fi
fi

(
    need=()
    for pkg in ${LUA53_PACKAGES}
    do
	if dpkg -s $pkg > /dev/null 2>&1; then
	    :
	else
	    need+=($pkg)
	fi
    done

    if [ "${#need[@]}" -gt 0 ]; then
	echo "Installing missing packages: ${need[@]}"
	apt-get update
	apt-get install -y ${need[@]}
    fi

    umask 022

    mkdir ${EXTERNAL_SRC_DIR} && echo "Created ${EXTERNAL_SRC_DIR} directory"
    mkdir ${EXTERNAL_SRC_DIR}/tarballs && echo "Created ${EXTERNAL_SRC_DIR}/tarballs directory"
    pushd ${EXTERNAL_SRC_DIR}

    cd ${EXTERNAL_SRC_DIR}/tarballs

    LUA53_TAR=$PWD/$(basename "${LUA53_URL}")

    rm "${LUA53_TAR}" && echo "** Removed old ${LUA53_TAR}"

    wget --progress=dot "${LUA53_URL}" || error "Failed to download ${LUA53_URL}" 128

    [ -f $LUA53_TAR ] || error "Can't find downloaded file: $LUA53_TAR" 129

    (cd ${EXTERNAL_SRC_DIR};tar xzf $LUA53_TAR)

    dir="${EXTERNAL_SRC_DIR}/"$(basename $LUA53_TAR .tar.gz)

    cd $dir || error "Failed to cd to ${dir}" 126

    tm_lastrpt=$SECONDS
    lines=0

    echo "Building ${LUA53_URL} in ${dir}"
    (
	trap 'st=$?;exec 1>&2;error "UNEXPECTED EXIT FROM BUILD" $st' 0
	set -xe
	cd ${dir}
	pwd
	nproc=$(type -P nproc)

	if [ -n "$nproc" ]; then
	    args='-j'$($nproc)
	fi

	make $args linux 2> ${tmpdir}/make.err | tee make.out
	make test
	make install
	trap - 0
    ) | tee build.out | while read ln
    do
	let "lines=$lines + 1"
	let "tm_delta=$SECONDS - $tm_lastrpt"
	if [ $tm_delta -ge 5 ]; then
	    echo "Building: $lines lines of output so far."
	    tm_lastrpt=$SECONDS
	fi
    done

    [ -d ${LUA53_TEST_DIR} ] || error "Failed to build Lua 5.3 from ${LUA53_URL}, look in ${dir} for clues." 135
)

# Check of we have 64 bit ints
bignum=$(echo 'print('${LUA_BIGNUM}')' | /usr/local/bin/lua -)
if [ "$bignum" != "${LUA_BIGNUM}" ]; then
    error "** /usr/local/bin/lua not built with 64bit ints!" 140
fi
