#!/bin/bash
#
# 40lua-lnum - Get LUA with LNUM patch
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Tue Dec 29 07:05:21 EST 2015
#

LUA_LNUM_TEST_FILE="/usr/local/lib/liblua.a"

LUA_BIGNUM='4611686018427387904' # 2^62

if $FORCE; then
    echo "Force rebuild of lua-lnum"
else
    if [ -f ${LUA_LNUM_TEST_FILE} ]; then
	# Check of we have 64 bit ints
	bignum=$(echo 'print('${LUA_BIGNUM}')' | /usr/local/bin/lua -)
	if [ "$bignum" != "${LUA_BIGNUM}" ]; then
	    echo "** /usr/local/bin/lua not built with 64bit ints!"
	    echo "** Will rebuild with LNUM_INT64"
	else
	    echo "Looks like ${LUA_LNUM_REPO} is already installed"
	    echo "To force rebuild do: sudo rm -f ${LUA_LNUM_TEST_FILE}"
	    return 0
	fi
    fi
fi

(
    need=()
    for pkg in ${LUA_LNUM_PACKAGES}
    do
	if dpkg -s $pkg > /dev/null 2>&1; then
	    :
	else
	    need+=($pkg)
	fi
    done

    if [ "${#need[@]}" -gt 0 ]; then
	echo "Installing missing packages: ${need[@]}"
	apt-get update
	apt-get install -y ${need[@]}
    fi

    umask 022

    tmpdir=$(mktemp -d /tmp/$(basename $ME).XXXXXX)

    echo "Using ${tmpdir} for download and build."

    chmod 755 ${tmpdir}

    cd ${tmpdir}

    git clone ${LUA_LNUM_REPO}

    dir=$(basename "${LUA_LNUM_REPO}" .git)

    [ -d "$dir" ] || error "Failed to clone lnum from ${LUA_LNUM_REPO}, look in ${tmpdir} for clues." 140

    tm_lastrpt=$SECONDS
    lines=0

    echo "Building & Installing..."
    (
	trap 'st=$?;exec 1>&2;error "UNEXPECTED EXIT FROM BUILD" $st' 0
	set -xe
	cd ${dir}
	pwd
	nproc=$(type -P nproc)

	if [ -n "$nproc" ]; then
	    args='-j'$($nproc)
	fi

	## Make sure to use 64Ints
	sed -i '/^#define lconfig_h/a#define LNUM_INT64' src/luaconf.h
	make $args linux 2> ${tmpdir}/make.err | tee make.out
	make test
	make install
	trap - 0
    ) | tee build.out | while read ln
    do
	let "lines=$lines + 1"
	let "tm_delta=$SECONDS - $tm_lastrpt"
	if [ $tm_delta -ge 5 ]; then
	    echo "Building: $lines lines of output so far."
	    tm_lastrpt=$SECONDS
	fi
    done

    [ -f ${LUA_LNUM_TEST_FILE} ] || error "Failed to build Lua lnum from ${LUA_LNUM_REPO}, look in ${tmpdir} for clues." 135

    cd $HOME

    rm -fr ${tmpdir}
)

# Check of we have 64 bit ints
bignum=$(echo 'print('${LUA_BIGNUM}')' | /usr/local/bin/lua -)
if [ "$bignum" != "${LUA_BIGNUM}" ]; then
    error "** /usr/local/bin/lua not built with 64bit ints!" 140
fi
