#!/bin/bash
#
# 45mysql - Make sure mysql is clean and ready for init on fasttrack side
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Wed Dec 30 06:40:28 EST 2015
#
# 

[ -z "${DEFAULT_MYSQL_PASSWORD}" ] && error "MISSING CONFIG VALUE: DEFAULT_MYSQL_PASSWORD" 145

# If a password is set we need to clean things up so basebox data doesn't leak to fasttrack
if mysql -uroot -p${DEFAULT_MYSQL_PASSWORD} -e "SHOW DATABASES" > /dev/null 2>&1; then
    echo "** Looks like mysql password has been set, trying to clear it..."
    rm -f ${ZDHOME}/.my.cnf
    mysqladmin -uroot -p"$DEFAULT_MYSQL_PASSWORD" password ''
fi

# Test that password is empty
rm -f ~/.my.cnf > /dev/null 2>&1

mysql -uroot -e "SHOW DATABASES" > /dev/null 2>&1 || error "Mysql password is not empty, basebox should not be built with any data in it!" 145

mysql -uroot -ve "DROP DATABASE swgemu" > /dev/null 2>&1 && echo "Dropped existing swgemu database"

# fasttrack/scripts/rc.fasttrack will take it from here..
echo "Mysql is ready for rc.fasttrack"
