#!/bin/bash
#
# 05autostart - Configure autostart
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sat Dec 26 17:25:19 EST 2015
#

if [ ! -d ${ZDHOME}/.config/autostart ]; then
    msg "Created autostart directory"
    mkdir -p ${ZDHOME}/.config/autostart
fi

[ ! -f ${ZDHOME}/.config/autostart/devsetup.desktop ] && msg "Setting up autostart"

cat << ! > ${ZDHOME}/.config/autostart/devsetup.desktop
[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=devsetup
Comment=
Exec=${ZDHOME}/ZonamaDev/fasttrack/scripts/devsetup
OnlyShowIn=XFCE;
StartupNotify=false
Terminal=false
Hidden=false
!

chown ${ZDUSER}:${ZDUSER} ${ZDHOME}/.config/autostart/devsetup.desktop

return 0
