#!/bin/bash
#
# TODO - should we even do this? Doing for now to make it easy but worry about stuff creeping into code with hard coded paths

cd /home
(
    l=$(readlink swgemu)

    if [ -z "$l" -o "$l" != "${ZDUSER}" ]; then
	[ -L swgemu ] && rm swgemu
	ln -vfs ${ZDUSER} swgemu && echo "Created /home/swgemu -> ${ZDHOME} symlink"
    fi
)
