#!/bin/bash
#
# Settings for devsetup scripts
#
# NOTE: This file is named 00-config-settings to make sure it loads first, don't make anything load sooner than this file!
#
## Get global config values
source $(dirname $ME)/../../common/global.config
#
# vi:set ft=sh
