#!/bin/bash
#
# Settings for devsetup scripts
#
# NOTE: This file is named 00-config-settings to make sure it loads first, don't make anything load sooner than this file!
#
## Get global config values
source $(dirname $ME)/../../common/global.config
#
## GERRIT SETTINGS
GERRIT_HOST=review.swgemu.com
GERRIT_PORT=29418
GERRIT_REGISTER_URL='http://'${GERRIT_HOST}'/login/%23%2Fregister%2Fq%2Fstatus%3Aopen'
GERRIT_UNKNOWN_USER='darthvaderdev'
#
## Autoconfig Browser to use
BROWSER=$( (for i in firefox iceweasel chromium google-chrome chromium-browser; do type -P $i; done)|head -1)
#
## Which editors should we "consider" offering? (will check each before we offer)
EDITORS='nano gedit gvim vim'
#
## Network settings
PINGTEST_HOST=www.cisco.com # This has worked for eons, hope they keep it up
NETWORK_SLOW_SECONDS=5 # If the internet tests take longer than this we will warn them with a notice
#
#
# vi:set ft=sh
