#!/bin/bash
#
# Boxes before 1.5 would run from master, from 1.5 forward we use release-x.y
#
# If this is a legacy box we need to switch it to release-1.4 branch.
#
legacy_checkup() {
    local base_dir=$(dirname $ME)
    local zd_branch=$(cd ${base_dir};git rev-parse --abbrev-ref HEAD)

    source /etc/os-release

    if [ "$VERSION_ID" -eq 8 ]; then
        export ZONAMADEV_BRANCH=""
        sed -e '/ZONAMADEV_BRANCH/d' -i ${base_dir}/../../common/global.config
    fi

    if [ -z "${ZONAMADEV_BRANCH}" ]; then
        export ZONAMADEV_BRANCH="release-1.4"
        echo 'export ZONAMADEV_BRANCH="'"${ZONAMADEV_BRANCH}"'"' >> ${base_dir}/../../common/global.config
    fi

    if [ "$zd_branch" = "${ZONAMADEV_BRANCH}" ]; then
        return 0
    fi

    (
        echo "** Migrate to ${ZONAMADEV_BRANCH}"
        cd ${base_dir}
        set -x
        git fetch --all --prune
        git stash
        git checkout "${ZONAMADEV_BRANCH}"
        git reset --hard @{u}
        git clean -d --force
    )

    source ${base_dir}/../../common/global.config

    sudo rm -f /.swgemudev.update

    sudo /bin/bash -xc "unset ME CHILD_STATUS;exec ${base_dir}/../../basebox/scripts/firstboot --force 15customize > /tmp/legacy_checkup.out 2>&1"

    notice "Legacy Checkup" "Moved ZonamaDev to legacy branch ${ZONAMADEV_BRANCH}\n\nMost likely you need to update your host and virtual machine soon."
}

legacy_checkup
