#!/bin/bash
#
# 01-iplist - Discover IP's we could use for this server
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sat Jan 16 10:37:28 EST 2016
#
# Depends: OPENRESTY_PORT
#
# NOTE: We run this in the background to give it a head start before the devsetup needs the list
#

[ -n "$OPENRESTY_PORT" ] || error "Missing OPENRESTY_PORT configuration" 101

update_iplist() {
  (
    SECONDS=0

    local pub_ip=$(dig @ns1.google.com -t txt o-o.myaddr.l.google.com +short | tr -d '"')

    # Simple lock so others can see if it's done later
    zdcfg set-flag iplist.lock
    trap 'zdcfg clear-flag iplist.lock' 0

    if [ -z "$pub_ip" ]; then
	echo "** Failed to find public ip so we can't reverse engineer the LAN network address"
	return 1
    fi

    echo "** Public IP: ${pub_ip}"

    local pub_rev=$(dig +short -x ${pub_ip})

    if [ -n "$pub_rev" ]; then
	pub_rev=" (${pub_rev})"
    fi

    zdcfg set iplist "${pub_ip},Public Internet IP${pub_rev}"

    IFS='.' read -ra t <<<${pub_ip}

    # Just guessing it's a class B most of the time
    local regex="${t[0]}\.${t[1]}\.${t[2]}.*"

    echo -ne "** Searching for Local Area Network...(${regex})"

    # Find last ip before our public subnet (again quick and dirty guess)
    local guess_lan_router=$(sudo traceroute -I -nw 2 -q 2 -m 10 www.cisco.com | perl -ne '@a = split; if($a[1] =~ /'${regex}'/) {  print $p; exit(0) }; $p = $a[1];')

    if [ -z "${guess_lan_router}" ]; then
	echo -e "\n** Can't determine LAN router IP. Traceroute ICMP might be blocked."
	return 1
    fi

    echo -e "\n** Found Lan Router: ${guess_lan_router}"

    # A unique id so we can see these across multiple logs etc.
    local scan_token=$(date|md5sum|cut -d' ' -f1)

    read -a instance_query <<<$(curl -s -D - -A zonamaipscan --connect-timeout 5 -m 5 'http://127.0.0.1:'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2> /dev/null)

    if [ "${instance_query[1]}" != "200" ]; then
	echo "Local zonama-instance-id service is not running on port ${OPENRESTY_PORT} as expected, giving up."
	return 1
    fi

    local our_instance="${instance_query[${#instance_query[@]}-1]}"

    # Typical home network
    IFS='.' read -ra t <<<${guess_lan_router}
    local subnet="${t[0]}.${t[1]}.${t[2]}."
    local lan_ip=''

    echo "** Scanning to find ourselves on the lan (${subnet}).."

    for i in {1..254}
    do
	# echo -ne "\r$i\t"
	local addr="${subnet}${i}"
	local result=$(curl -s -A zonamaipscan --connect-timeout 0.02 -m 0.02 'http://'${addr}':'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2>/dev/null)

	if [ "X$result" = "X$our_instance" ]; then
	    # TODO do we need to double check nginx log local just in case?
	    lan_ip=$addr
	    break
	fi
    done

    echo "** Local Network IP: ${lan_ip}"

    zdcfg set iplist "${pub_ip},Public Internet IP${pub_rev}\n${lan_ip},Local Network IP"

    step_complete 0 "seconds=$SECONDS"

    exit 0
  ) < /dev/null > /tmp/iplist.out 2>&1 &
}

IPLIST=$(zdcfg get iplist 2> /dev/null)

if $FORCE; then
    IPLIST=''
fi

if [ -z "$IPLIST" ]; then
    update_iplist 
fi
