#!/bin/bash
#
# 01check-basebox - Check if we're running in the pre-package stage
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 05:38:48 EST 2015
#
## Check for suspended setup

if zdcfg check-flag suspend_devsetup; then
    if $HAVEX; then
	if zenity --question  --text="Developer setup is suspended.\n\nDo you want to continue to suspend developer setup?\n(usually YES on basebox build beofre packaging)"; then
	    alert "setup suspended" "Developer setup has been suspended."
	    exit 0
	else
	    if zenity --question  --text="Should I remove the suspend flag?\n(usually NO basebox build)"; then
		msg "USER ASKED US TO clear suspend_devsetup"
		zdcfg clear-flag suspend_devsetup
		alert "setup resumed" "Cleared suspend_devsetup flag"
	    fi
	fi
    else
	alert "setup suspended" "Suspended because suspend_devsetup flag, ignore this if you're working on building the basebox."
	msg "SUSPENDING SETUP BECAUSE OF suspend_devsetup FLAG"
	exit 0
    fi
fi
#
# vi:set ft=sh
