#!/bin/bash
#
# 01internet-test - Check for proper internet connectivity
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Dec 27 06:56:09 EST 2015
#

internet_test() {
    local tm_start=$SECONDS

    if ping -c 1 -W 2 ${PINGTEST_HOST}; then
	echo "${PINGTEST_HOST} reponds!"
    else
	alert "Internet Access Required" "Setup can not continue until you fix your internet access!"
	zenity --error --title "Internet Access Required" --text "We were unable to ping ${PINGTEST_HOST}\n\nYOU MUST HAVE INTERNET ACCESS TO SETUP THIS BOX\n\nFIX IT OR GET HELP!"
	exit 200
    fi

    # TODO should we try and pull a large asset and test their internet speed or do we care?
    if curl -m 30 -s "${GERRIT_HOST}" > /dev/null; then
	echo "${GERRIT_HOST} responds!"
    else
	local gerrit_username=$(zdcfg get gerrit_username 2>/dev/null)

	if [ -z "$gerrit_username" -o "$gerrit_username" = "$GERRIT_UNKNOWN_USER" ]; then
	    alert "Access to ${GERRIT_HOST} Required" "Setup can not continue until ${GERRIT_HOST} is available from this machine"
	    zenity --error --title "Access to ${GERRIT_HOST} Required" --text "We were unable to connect to ${GERRIT_HOST}\n\nTHIS HOST MUST BE AVAILABLE TO SETUP THIS BOX\n\nFIX IT OR GET HELP!"
	    exit 201
	else
	    alert "Warning ${GERRIT_HOST} Failure" "WARNING: ${GERRIT_HOST} is not available!  You will not be able to pull or push code until this is resolved."
	fi
    fi

    # Warn them if they seem to be a bit slow (so they don't bitch later about how long things take)
    local delta=999
    let "delta=$SECONDS - $tm_start"

    if [ $delta -gt ${NETWORK_SLOW_SECONDS} ]; then
	alert "Internet Speed Warning" "Your internet seems a bit slow, it took ${delta} seconds to verify your connection!"
    fi

    step_complete 0 "delta=$delta"
}

internet_test
