#!/bin/bash
#
# 02bin - Setup user's $HOME/bin
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Dec 27 07:29:17 EST 2015
#

setup_bindir() {
    [ -d ~/bin ] || mkdir -p ~/bin

    pushd $(dirname $ME)'/../bin'
	for fn in *
	do
	    ln -vfs "${PWD}/${fn}" ~/bin/"${fn}"
	done
    popd

    if step_not_complete; then
	# Remove old entry (if any)
	if grep '## START DEVSETUP ##' ~/.bashrc > /dev/null 2>&1; then
	    sed '/^## START DEVSETUP ##/,/^## END DEVSETUP ##/d' -i ~/.bashrc
	fi

	# Append our new path and status check (including warning if they're too quick to draw)
	echo -e '## START DEVSETUP ##\nexport PATH=$HOME/bin:$PATH\n$HOME/bin/swgemu status\n## END DEVSETUP ##' >> ~/.bashrc
	chmod 600 ~/.bashrc

	step_complete 0
    fi
}

setup_bindir
