#!/bin/bash
#
# 02crontab - Setup user's crontab
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sat Sep 10 10:04:27 EDT 2016
#

setup_crontab() {
    (let "hh=$RANDOM % 24";let "mm=$RANDOM % 60";crontab -l|grep -v zdupdate;echo ${mm}' '${hh}' * * * /home/vagrant/bin/zdupdate --auto 2>&1 | logger -i -t "swgemu.zdupdate"')|crontab
    crontab -l|egrep -v '^#'
}

setup_crontab
