#!/bin/bash
#
# 03tzdata - Ask them if they want to configure the timezone
#
if step_not_complete; then
    sudo apt-get -y install libgnome2-perl &

    if yorn "The current time zone is "$(date +%Z)" on this machine.\n\nWould you like to change the time zone? "; then
	notice "Setting Timezone" "Loading timezone setup panel."
	wait
	sudo -E dpkg-reconfigure --frontend=gnome tzdata
	notice "Timezone Set" "Timezone Set to "$(date +%Z)
    else
	alert "Timezone not set" "You can open a terminal later and run:\nsudo dpkg-reconfigure tzdata"
    fi

    step_complete 0
fi
