#!/bin/bash
#
# 10ssh-key - setup a new ssh key if needed
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Fri Dec 25 20:52:45 EST 2015
#

setup_sshkey() {
    if [ ! -f $HOME/.ssh/id_rsa ]; then
	msg "Generating SSH Key"
	rm -f $HOME/.ssh/id_rsa $HOME/.ssh/id_rsa.pub
	if ssh-keygen -t rsa -q -N "" -C "emudev-"$(date +%Y%m%d)"-$(git config --get user.email)" -f ~/.ssh/id_rsa; then
	    notice 'SSH Key Created' 'We created a new ssh key for you!\n\nPlease make sure to update your Gerrit key settings!'
	fi
	[ -n "$SSH_AGENT_PID" ] && ssh-add
    else
	msg "SSH $HOME/.ssh/id_rsa already exists"
    fi
}

setup_sshconfig() {
    # Remove old entry (if any)
    if grep '## START DEVSETUP ##' ~/.ssh/config > /dev/null 2>&1; then
	sed '/^## START DEVSETUP ##/,/^## END DEVSETUP ##/d' -i ~/.ssh/config
    fi

    local gerrit_username=$(cat ~/.gerrit_username 2>/dev/null)

    # Do we know the GERRIT_USERNAME yet?
    if [ -z "$gerrit_username" ]; then
	# Default to this so gerrit tests fail and ask user to register
	gerrit_username=$GERRIT_UNKNOWN_USER
    fi

    echo -e "## START DEVSETUP ##\nStrictHostKeyChecking no\n\nHost ${GERRIT_HOST}\n\tUser ${gerrit_username}\n\tPort ${GERRIT_PORT}\n\tIdentityFile ~/.ssh/id_rsa\n## END DEVSETUP ##" >> ~/.ssh/config
    chmod 600 ~/.ssh/config
    echo "Set ~/.ssh/config to:"
    cat ~/.ssh/config
}

setup_sshkey

setup_sshconfig
