#!/bin/bash
#
# 15editor - Choose the user's favorite editor
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sat Dec 26 20:37:37 EST 2015
#

setup_visual() {
    local visual=$(zdcfg get visual 2>/dev/null)

    while [ -z "$visual" ]
    do
	local args=''
	for i in $EDITORS; do
	    local path=$(type -P $i)

	    if [ -n "$path" ]; then
		args="$args $i $path"
	    fi
	done

	local r=$(zenity --list --title="Choose your favorite editor" --column="Editor" --column="Path" $args)

	if [ -z "$r" ]; then
	    notice "Editor" "When in doubt we choose nano!"
	    zdcfg set visual $(type -P nano)
	else
	    notice "Editor" "Set editor to $r"
	    zdcfg set visual $(type -P $r)
	fi

	visual=$(zdcfg get visual 2>/dev/null)

	if [ -n "$visual" ]; then
	    step_complete 0 "visual=$visual"
	    break
	fi
    done

    if grep 'bin/zdcfg get visual' ~/.bashrc; then
	:
    else
	sed '/^export VISUAL/d' -i ~/.bashrc
	echo 'export VISUAL=$(~/bin/zdcfg get visual)' >> ~/.bashrc
    fi
}

setup_visual
