#!/bin/bash
#
# 20gerrit - Configure Gerrit
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Dec 27 07:43:31 EST 2015
#

GERRIT_FIRSTTIME=false
GERRIT_RETRY=false

setup_gerrit() {
    local l="${ASSETS_DIR}/openid_providers.txt"
    local h=$(expr 100 + $(wc -l<$l) \* 20)
    local r=$(egrep -v '^#' $l|cut -d'|' -f1|zenity --list --title="Choose your openId Provider" --column="OpenId Provider" --height=$h --width=300)
    echo "Provider=[$r]"

    local url=$GERRIT_REGISTER_URL

    if [ -n "$r" -a "$?" -eq 0 ]; then
	url="${url}"$(egrep "^$r\|" $l|cut -d '|' -f2)
    fi

    echo "url=[$url]"

    if xsel -b -i < ~/.ssh/id_rsa.pub; then
	alert "SSH Key" "Your ssh key has been added to the clipboard so you can paste it into Gerrit's registration form"
    fi

    alert 'Login and Register with Gerrit' 'Please follow these steps:\n  1) Login to your openID provider\n  2) Set your gerrit username\n  3) Paste you SSH key into the ssh field and hit [Add]\n  4) Exit the browser to continue'

    $BROWSER "$url" > /dev/null 2>&1

    xsel -c

    local r=$(zenity --entry --title="Gerrit Username" --text="What is your Registered Gerrit Username?")

    echo "response=[$r]"

    if [ -n "$r" -a "$?" -eq 0 ]; then
	echo "gerrit_username=[$r]"
	zdcfg set gerrit_username "$r"
	setup_sshconfig
	GERRIT_FIRSTTIME=true
    else
	error "Gerrit Registration Required\nYou must register, pick a username and set you ssh key before you can continue!" 202
    fi
}

check_gerrit() {
    local tmp=$(mktemp /tmp/check_gerritXXXXXX.tmp)
    local err=$(mktemp /tmp/check_gerritXXXXXX.err)

    if scp ${GERRIT_HOST}:hooks/commit-msg $tmp > /dev/null 2> $err; then
	echo "Gerrit seems happy with us!"

	if $GERRIT_FIRSTTIME; then
	    alert "Gerrit Success" "Gerrit registration was successful."
	    local gerrit_username=$(zdcfg get gerrit_username 2>/dev/null)
	    step_complete 0 "gerrit_user=$gerrit_username"
	fi
    else
	alert "Gerrit Failure" "Gerrit does not appear to be setup correctly."

	if zenity --question  --text="Do you want to try and repair your Gerrit setup?"; then
	    zdcfg clear gerrit_username
	    GERRIT_RETRY=true
	    return 0
	else
	    error "Gerrit Broken\nUntil you fix Gerrit you will not be able to continue with setup." 203
	fi
    fi

    rm -f $tmp $err > /dev/null 2>&1
}

if [ -z "$BROWSER" -o ! -x "$BROWSER" ]; then
    error "Can't find web browser!\nYou must have a web browser installed to setup gerrit, did you remove it!?" 204
fi

GERRIT_USERNAME=$(zdcfg get gerrit_username 2>/dev/null)

if [ -z "$GERRIT_USERNAME" -o "$GERRIT_USERNAME" = "$GERRIT_UNKNOWN_USER" ]; then
    GERRIT_RETRY=true
fi

while $GERRIT_RETRY
do
    GERRIT_RETRY=false
    setup_gerrit
    check_gerrit
done
