#!/bin/bash
#
# 20gerrit - Configure Gerrit
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Dec 27 07:43:31 EST 2015
#

GERRIT_FIRSTTIME=false

setup_gerrit() {
    # is it setup already?
    local gerrit_username=$(cat ~/.gerrit_username 2>/dev/null)

    if [ -z "$gerrit_username" -o "$gerrit_username" = "$GERRIT_UNKNOWN_USER" ]; then
	# Looks like we need to get them started
	local l="${ASSETS_DIR}/openid_providers.txt"
	local h=$(expr 100 + $(wc -l<$l) \* 20)
	local r=$(egrep -v '^#' $l|cut -d'|' -f1|zenity --list --title="Choose your openId Provider" --column="OpenId Provider" --height=$h --width=300)
	echo "Provider=[$r]"

	local url=$GERRIT_REGISTER_URL

	if [ -n "$r" -a "$?" -eq 0 ]; then
	    url="${url}"$(egrep "^$r\|" $l|cut -d '|' -f2)
	fi

	echo "url=[$url]"
	
        if xsel -b -i < ~/.ssh/id_rsa.pub; then
	    alert "SSH Key" "Your ssh key has been added to the clipboard so you can paste it into Gerrit's registration form"
	fi

	alert 'Login and Register with Gerrit' 'Please follow these steps:\n  1) Login to your openID provider\n  2) Set your gerrit username\n  3) Paste you SSH key into the ssh field and hit [Add]\n  4) Exit the browser to continue'

	$BROWSER "$url" > /dev/null 2>&1

	xsel -c

	local r=$(zenity --entry --title="Gerrit Username" --text="What is your Registered Gerrit Username?")

	echo "response=[$r]"

	if [ -n "$r" -a "$?" -eq 0 ]; then
	    echo "~/.gerrit_username=[$r]"
	    echo "$r" > ~/.gerrit_username
	    setup_sshconfig
	    GERRIT_FIRSTTIME=true
	else
	    alert "Gerrit Registration Required" "You must register, pick a username and set you ssh key before you can continue!"
	    exit 202
	fi
    fi
}

check_gerrit() {
    local tmp=$(mktemp /tmp/check_gerritXXXXXX.tmp)
    local err=$(mktemp /tmp/check_gerritXXXXXX.err)

    if scp ${GERRIT_HOST}:hooks/commit-msg $tmp > /dev/null 2> $err; then
	echo "Gerrit seems happy with us!"

	if $GERRIT_FIRSTTIME; then
	    alert "Gerrit Success" "Gerrit registration was successful."
	fi
    else
	alert "Gerrit Failure" "Gerrit does not appear to be setup correctly."

	if zenity --question  --text="Do you want to try and repair your Gerrit setup?"; then
	    rm -f ~/.gerrit_username
	    GERRIT_RETRY=true
	    return
	else
	    alert "Gerrit Broken" "Until you fix Gerrit you will not be able to continue with setup."
	    exit 203
	fi
    fi

    rm -f $tmp $err > /dev/null 2>&1
}

if [ -z "$BROWSER" -o ! -x "$BROWSER" ]; then
    alert "Can't find web browser!" "You must have a web browser installed to setup gerrit, did you remove it!?"
    return
fi

if $HAVEX; then
    # TODO should we count the number of loops and at some point kill ssh keys etc?
    GERRIT_RETRY=true

    while $GERRIT_RETRY
    do
	GERRIT_RETRY=false
	setup_gerrit
	check_gerrit
    done
else
    alert "Must run under X" "You need X windows to display your web browser for gerrit setup!"
fi
