#!/bin/bash
#
# 30emuyoda - Install and Setup EmuYoda
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Jan 24 20:29:52 EST 2016
#

setup_yoda() {
    if [ ! -d "${EMUYODA_DIR}/." ]; then
	echo "** setting up emuyoda **"
	(
	    ln -s ~/ZonamaDev/server/emuyoda ${EMUYODA_DIR}

	    cp ~/ZonamaDev/server/openresty/nginx/conf/nginx.conf ${OPENRESTY_DIR}/nginx/conf

	    ${OPENRESTY_DIR}/nginx/sbin/nginx -s stop
	    rm -f ${OPENRESTY_DIR}/nginx/logs/* > /dev/null 2>&1
	    sleep 5
	    ${OPENRESTY_DIR}/nginx/sbin/nginx

	    notice "EmuYoda Installed" "The EmuYoda API and Web Interface has been installed."
	)

	$BROWSER 'http://127.0.0.1:'${OPENRESTY_PORT}'/' > /dev/null 2>&1 < /dev/null &
    fi
}
