#!/bin/bash
#
# 31server-ip - Ask user for the ip address they want to use for this server
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sat Jan 16 11:54:00 EST 2016
#
# NOTE: Depends on 01-iplist running to detect LAN and Public IP, if that fails they'll get localhost and MANUAL as an option
#

SERVER_IP=''

prompt_ip() {
    local selected_ip=$(
	(
	echo -e "TRUE\n127.0.0.1\nDefault - Local Client and Server on one computer"
	zdcfg get iplist | sed -e 'iFALSE' -e 's/,/\n/'
	echo -e "FALSE\nMANUAL\nEnter a manual address (Expert Mode)"
	) | zenity --list --radiolist --text="Choose your Server IP:" --title="Discovered IP Addresses" --column="Select" --column="IP Address" --column="Description" --print-column=2 --width=650 --height=250 2> /dev/null
    )

    echo "Got [${selected_ip}]"

    if [ "${selected_ip}" = "MANUAL" ]; then
	selected_ip=''
	while [ -z "$selected_ip" ]
	do
	    local r=$(zenity --entry --title="Server IP" --text="What IP would you like to use for this server?")

	    if [ -z "$r" ]; then
		return 2
	    fi

	    pingit=$(ping -W 3 -c 1 "${r}" 2>&1)

	    if [ "$?" -ne 0 ]; then
		zenity --error --title="Invalid IP Address" --text="${pingit}" < /dev/null > /dev/null 2>&1
	    else
		# Make sure they didn't use a hostname
		local a=$(dig -t A +short ${r})

		if [ -n "$a" ]; then
		    selected_ip="${a}"
		else
		    selected_ip="$r"
		fi
	    fi
	done
    fi

    if [ -n "$(zdcfg get iplist | egrep "^${selected_ip}," | grep -y public)" ]; then
	if zenity --question --icon-name=dialog-warning --window-icon=warning --title="Are you sure?" --text="Using a public ip is complicated and dangerous, you need to configure your firewall properly.\n\nIt can be dangerous because it exposes your network through this server to malicous people from all over the world.\n\nAre you sure you want to continue?" < /dev/null > /dev/null 2>&1; then
	    SERVER_IP=$selected_ip
	    return 0
	else
	    return 2
	fi
    else
	SERVER_IP=$selected_ip
	return 0
    fi

    return 1
}

setup_server_ip() {
    # Check to make sure iplist is done
    for i in 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1
    do
	if zdcfg check-flag iplist.lock; then
	    echo "$i: iplist.lock still set"
	    sleep 1
	else
	    break
	fi
    done

    zdcfg clear-flag iplist.lock

    echo "** Setup Server IP **"

    # Prompt them until they get one set or default
    while :
    do
	prompt_ip
	# Retry?
	if [ $? -ne 2 ]; then
	    break
	fi
    done

    if [ -z "$SERVER_IP" ]; then
	SERVER_IP='127.0.0.1'
    fi

    # TODO should we check the zonama-instance-id service and see if this the right ip?

    zdcfg set server_ip $SERVER_IP

    step_complete 0 "server_ip=$SERVER_IP"
}

SERVER_IP=$(zdcfg get server_ip 2> /dev/null)

if [ -z "$SERVER_IP" ]; then
    setup_server_ip
fi
