#!/bin/bash
#
# 35config-build - Configure code and kick-off initial build
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Wed Dec 30 14:35:23 EST 2015
#

config_build() {
    local missing=''

    for i in $REPOS
    do
	if [ -d $WORKSPACE/$i/.git ]; then
	    echo "Found $i in $WORKSPACE/$i"
	else
	    missing="$missing $i"
	fi
    done

    if [ -n "$missing" ]; then
	zenity --error  --text="You're missing the following repos: $missing\n\nWe can't do the build until that is fixed."
	exit 135
    fi

    local status_pipe=$(mktemp /tmp/clone-status-pipe-XXXXXX)

    mknod $status_pipe p

    command_window "Config and Build" "tail -f $status_pipe"  &

    local logfile=$WORKSPACE/Initial_Core3_Build.log

    [ -f $logfile ] && mv ${logfile} ${logfile}'-prev'

    (date;set -x;~/bin/swgemu build) 2>&1 | tee $status_pipe | tee $logfile

    result=$(tail -1 $logfile)
    zenity --info --text="Config and Build process finished.\n\n${result}\n\nYou can find a copy of the output in $logfile\n\nPress [OK] to close the log window"
    fuser -k $status_pipe
    rm -f $status_pipe
    step_complete 0 "yoda=false"
}

if [ ! -f $WORKSPACE/Initial_Core3_Build.log ]; then
    if zdcfg check-flag have_yoda; then
	echo "** Let Yoda handle it"
	launch_yoda
	step_complete 0 "yoda=true"
	return 0
    fi

    if yorn "Would you like to run the initial config and build process?\n\n(This will run for quite a while)"; then
	echo "User requested conf-build"
	config_build
    fi
fi
