#!/bin/bash

check-ldt-prefs() {
  local path="$HOME/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ldt.ui.prefs"

  read sum p <<< $(md5sum "${path}")

  if [ "$p" -ne "20b40404d68380f39555ad7d2c47431e" ]; then
      return
  fi

  cat << ! > "${path}"
eclipse.preferences.version=1
formatter.indentation.indentTables=true
formatter.indentation.size=2
formatter.profiles=<?xml version\="1.0" encoding\="UTF-8" standalone\="no"?>\n<profiles>\n<profile formatter\="org.eclipse.ldt.editor.LuaFormatterFactory" name\="tabbed" version\="1">\n<setting id\="formatter.indentation.size" value\="2"/>\n<setting id\="formatter.tabulation.char" value\="tab"/>\n<setting id\="formatter.tabulation.size" value\="2"/>\n<setting id\="formatter.indentation.indentTables" value\="true"/>\n</profile>\n</profiles>\n
formatter.profiles.active=tabbed
formatter.tabulation.char=tab
formatter.tabulation.size=2
formatterId=org.eclipse.ldt.editor.LuaFormatterFactory
sourceHoverBackgroundColor.SystemDefault=true
useAnnotationsPrefPage=true
useQuickDiffPrefPage=true
!

  notice "Eclipse Lua Settings Updated" "Updated your eclipse settings to default to SwgEmu coding standards"
}

check-ldt-prefs
