#!/bin/bash
#
# cleanup_for_publish - root user cleanup of image for publish
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Apr 21 15:56:53 UTC 2013
#

if [ "$1" != "4bc95050e236c01a73daec4cbef2dcdb" ]; then
  echo "Compainion script to /home/swgemu/cleanup_for_publish, not designed to be ran standalone"
  exit 0
fi

VERSION=$2

# Easier to do these in a script since wild cards are involved etc.
rm -fr /var/tmp/* /tmp/* /etc/ssh/ssh_host*_key* /root/.viminfo /root/.bash_history /root/.lesshst /root/.ssh/* /var/log/*.gz /var/log/*.1 /var/log/*.old
find /var/log -type f | while read f
do
  cp /dev/null $f
done
/usr/sbin/dpkg-reconfigure openssh-server
exit 0
