#!/bin/bash
#
# 00--auto-update - Make sure auto-update system is working
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Feb  7 08:03:17 EST 2016
#

check_autoupdate() {
    local aa_flag="/tmp/00--auto-update.run"

    if [ ! -f /.swgemudev.update ]; then
	if [ -f ${aa_flag} ]; then
	    msg "LOOP DETECTED (${aa_flag} EXISTS: $(cat ${aa_flag})), GIVING UP, GET HELP!"
	    return 0
	fi
	cd ${ZDHOME}
	date "+%s $$" > ${aa_flag}
	msg "Converting to swgemudev.update auto-update method"
	/bin/bash -xc 'unset ME CHILD_STATUS;exec ZonamaDev/basebox/scripts/firstboot --force 15customize > /tmp/autoupdate.out 2>&1'
	/.swgemudev.update
	rm -f "${LOCKFILE}"
	exec ${ZDHOME}/ZonamaDev/fasttrack/scripts/rc.fasttrack
	error "Auto Update Conversion Failed\nCould not re-exec rc.fasttrack, GET HELP!" 111
    fi

    return 0
}

check_autoupdate
