#!/bin/bash
#
# Settings for rc.faststart scripts
#
# NOTE: This file is named 00-config-settings to make sure it loads first, don't make anything load sooner than this file!
#
## Must run as root
[ $(id -u) -eq 0 ] || error "$ME must run as root, try: sudo $ME" 100
#
## Get global config values
source $(dirname $ME)/../../common/global.config
#
## Fix machine-id if it's blank (first fresh boot)
if [ ! -s /var/lib/dbus/machine-id ]; then
    # New machine-id
    dbus-uuidgen > /var/lib/dbus/machine-id
    systemd-machine-id-setup
fi

SWGEMUDEV_VERSION=$(cat /.swgemudev.version)
SWGEMUDEV_GITURL=$(cat /.swgemudev.giturl)

#
## Check for suspend flag
SUSPEND_FLAG=~vagrant/.suspend_fasttrack

if [ -f $SUSPEND_FLAG ]; then
    tm_now=$(date +%s)
    tm_then=$(<$SUSPEND_FLAG)
    let "tm_delta=$tm_now - $tm_then"
    notice "$(basename $ME) suspended" "Suspended because ${SUSPEND_FLAG} exists for the last ${tm_delta} second(s), ignore this if you're working on building the basebox."
    msg "SUSPENDING SETUP BECAUSE ${SUSPEND_FLAG} EXISTS"
    exit 0
fi
