#!/bin/bash
#
# 00extras - Install extra packages (if needed)
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Fri Dec 25 20:52:17 EST 2015
#

setup_extras() {
    # Figure out if user gave us extra packages to install
    local extras=$(egrep -hv '^#' extras ~vagrant/extras $(dirname $ME)/../../../extras 2> /dev/null|sort -u|tr '\n' '\40')

    if [ -z "$extras" ]; then
	msg "No extras packages found"
	return
    fi

    # Get latest repo locations
    apt-get update

    # Upgrade whatever we can
    apt-get -y -o Dpkg::Options::="--force-confnew" dist-upgrade

    msg "Install Extras"

    echo ">> EXTRAS: $extras"

    apt-get -y install $extras

    apt-get -y autoremove
}

setup_extras
