#!/bin/bash
# Some really slow speeds on virtual box when doing the scp of tre files
# hope this helps...

if type ethtool; then
    :
else
    apt-get install -y ethtool && echo "Installed ethtool"
fi

(
set -x
ethtool -K eth0 gro off || ethtool -K enp0s3 gro off
ethtool -K eth1 gro off 2> /dev/null
)
