#!/bin/bash
#
# 00extras - Install extra packages (if needed)
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Fri Dec 25 20:52:17 EST 2015
#

setup_extras() {
    # Figure out if user gave us extra packages to install
    local path=$ME
    local extras=''

    while [ "$path" != "/" -a $path != "." ]
    do
	path=$(dirname $path)
	local fn="${path}/extras"

	if [ -f "${fn}" ]; then
	    echo "Found $fn"
	    extras="$extras "$(egrep -hv '^#' "${fn}")
	fi
    done

    if [ -z "$extras" ]; then
	msg "No extras packages found"
	return
    fi

    # Remove dupes and check if installed
    extras=$(printf "%s\n" $extras)
    needinstall=false

    for i in $extras
    do
	if dpkg -s $i > /dev/null 2>&1; then
	    :
	else
	    needinstall=true
	fi
    done

    if $needinstall; then
	# Get latest repo locations
	apt-get update

	# Upgrade whatever we can
	# TODO do we want to do this? Skip for now -- kator
	# apt-get -y -o Dpkg::Options::="--force-confnew" dist-upgrade

	msg "Install Extras"

	echo ">> EXTRAS: $extras"

	apt-get -y install $extras

	apt-get -y autoremove
    else
	echo "All extras appear to be installed [$extras]"
    fi
}

setup_extras
